# Generated by Django 2.2.24 on 2021-11-27 21:41

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("authnapp", "0003_default_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopuser",
            name="activation_key_expires",
            field=models.DateTimeField(
                default=datetime.datetime(2021, 11, 29, 21, 41, 42, 364874, tzinfo=utc),
                verbose_name="актуальность ключа",
            ),
        ),
    ]
